apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-rs
  labels: 
    app: app-rs
    type: replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-rs
  template:
    metadata:
      name: app-rs
      labels: 
        app: app-rs
        type: replicaset
    spec:
      containers:
      - name: nginx-rs
        image: nginx
        ports:
        -  containerPort: 80
